server:
  port: 8080
spring:
  application:
    name: facility-service
  datasource:
    url: jdbc:sqlserver://10.178.2.27
    # TODO: read from dbConfig.properties or ENV
    username: SA
    password: e#R3Dzcf!cLo4MO,
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS # Enable Color-Coded Output
logging:
  file:
    path: ./logs
