spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:sqlserver://10.178.2.27
    username: SA
    password: e#R3Dzcf!cLo4MO,
    # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
