spring:
  application:
    name: analysis-service
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=employees
    username: sa
    password: 
  jpa: 
    show-sql: true
    properties:
      hibernate:
        format_sql : true
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect : org.hibernate.dialect.SQLServer2012Dialect
        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto : update

server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true