spring:
  application:
    name: energielenker-eneffco-service
  datasource:
    url: jdbc:sqlserver://
    # TODO: read from dbConfig.properties or ENV
    username: 
    password: 
    driver-class-name: 

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true